/**
 * INFOGRAFIA BRAIN - Genera infografías visuales con gemini-3-pro-image
 * 
 * Este cerebro:
 * 1. Analiza el frame (contexto del párrafo)
 * 2. Crea un prompt optimizado para imagen
 * 3. Genera la imagen con gemini-3-pro-image
 * 4. Sube a Supabase Storage
 * 5. Retorna URL pública
 */

import { GoogleGenerativeAI } from "@google/generative-ai";
import { createClient } from "@/utils/supabase/server";

export interface InfografiaParams {
    frame: string;
    concept: string;
    topicId: string;
    widgetId: string;
}

export async function generateInfografia(params: InfografiaParams): Promise<string> {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
        throw new Error('GEMINI_API_KEY not configured');
    }
    
    const genAI = new GoogleGenerativeAI(apiKey);
    
    // Paso 1: Analizar frame y crear prompt optimizado
    const analysisModel = genAI.getGenerativeModel({
        model: 'gemini-2.0-flash-exp'
    });
    
    const analysisPrompt = `
Contexto del tema:
${params.frame}

Concepto clave: ${params.concept}

Genera un prompt detallado para crear una INFOGRAFÍA VISUAL que:
- Explique visualmente el concepto de forma clara
- Use iconos modernos y texto mínimo
- Sea útil para memorización rápida
- Estilo: Profesional, colores corporativos (azul #2563eb, verde #10b981)
- Formato: Vertical u horizontal según convenga
- Incluya título claro del concepto

IMPORTANTE: El prompt debe ser específico sobre layout, colores, iconos y texto.

Responde SOLO el prompt para imagen, sin explicaciones adicionales:
`;
    
    try {
        console.log('[INFOGRAFIA-BRAIN] Analyzing frame for:', params.concept);
        
        const analysis = await analysisModel.generateContent(analysisPrompt);
        const imagePrompt = analysis.response.text();
        
        console.log('[INFOGRAFIA-BRAIN] Generated image prompt (first 200 chars):', imagePrompt.slice(0, 200));
        
        // Paso 2: Generar imagen con gemini-3-pro-image
        // Nota: Verificar disponibilidad del modelo. Si no existe, usar alternativa
        let imageModel;
        try {
            imageModel = genAI.getGenerativeModel({
                model: 'gemini-3-pro-image'
            });
        } catch (modelError) {
            console.warn('[INFOGRAFIA-BRAIN] gemini-3-pro-image not available, trying gemini-2.5-flash-image');
            imageModel = genAI.getGenerativeModel({
                model: 'gemini-2.5-flash-image'
            });
        }
        
        const result = await imageModel.generateContent([imagePrompt]);
        const imagePart = result.response.candidates?.[0]?.content?.parts
            ?.find((p: any) => p.inlineData);
        
        if (!imagePart?.inlineData) {
            throw new Error('No image generated by model');
        }
        
        // Paso 3: Convertir a Buffer
        const imageData = Buffer.from(imagePart.inlineData.data, 'base64');
        console.log('[INFOGRAFIA-BRAIN] Image generated, size:', imageData.length, 'bytes');
        
        // Paso 4: Subir a Supabase Storage
        const supabase = await createClient();
        const filename = `${params.topicId}/infografia_${params.widgetId}_${Date.now()}.png`;
        
        const { error: uploadError } = await supabase.storage
            .from('generated-images')
            .upload(filename, imageData, { 
                contentType: 'image/png', 
                upsert: true 
            });
        
        if (uploadError) {
            console.error('[INFOGRAFIA-BRAIN] Upload error:', uploadError);
            throw uploadError;
        }
        
        // Paso 5: Obtener URL pública
        const { data: { publicUrl } } = supabase.storage
            .from('generated-images')
            .getPublicUrl(filename);
        
        console.log('[INFOGRAFIA-BRAIN] Image uploaded successfully:', publicUrl);
        
        return publicUrl;
        
    } catch (error) {
        console.error('[INFOGRAFIA-BRAIN] Error:', error);
        throw new Error(`Failed to generate infografia: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
}

